pool:
  name: Hosted Windows 2019 with VS2019
#Your build pipeline references an undefined variable named ‘BuildConfiguration’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: UseDotNet@2
  displayName: 'Use .Net Core sdk from global.json'
  inputs:
    useGlobalJson: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: EvilBaschdi.Core/EvilBaschdi.Core.csproj
    feedsToUse: config
    nugetConfigPath: NuGet.config

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: EvilBaschdi.Core/EvilBaschdi.Core.csproj
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: EvilBaschdi.Core.Tests/EvilBaschdi.Core.Tests.csproj
  enabled: false
  continueOnError: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: EvilBaschdi.Core/EvilBaschdi.Core.csproj
    nobuild: true

- powershell: |
   $gitPat = '$(System.AccessToken)'
   git remote add github https://$gitPat@github.com/evilbaschdi/EvilBaschdi.Core
   git push github --all
   git push github --tags
  displayName: 'PowerShell Script'
  enabled: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Nuget-Package'
  inputs:
    ArtifactName: 'Nuget-Package'

